services:
  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: wp
      MARIADB_USER: wp
      MARIADB_PASSWORD: wp
      MARIADB_ROOT_PASSWORD: root
    volumes: [ "wp-data:/var/lib/mysql" ]
  wp:
    image: wordpress:6.7-php8.2-apache
    depends_on: [ db ]
    ports: [ "8930:80" ]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - "wp-core:/var/www/html"
      - "../:/var/www/html/wp-content/plugins/terra-realestate"
  wpcli:
    image: wordpress:cli-php8.2
    depends_on: [ wp, db ]
    user: "33:33"
    entrypoint: [ "tail", "-f", "/dev/null" ]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - "wp-core:/var/www/html"
      - "../:/var/www/html/wp-content/plugins/terra-realestate"
volumes: { wp-data: {}, wp-core: {} }
